campus = input("Enter campus name: ")
student = input("Enter your name: ")
students = int(input("Enter number of students in university: "))
n = int(input("Enter number of energy readings: "))
energy = input("Enter energy readings separated by space: ").split()
for i in range(len(energy)):
    energy[i] = int(energy[i])
efficient = [e for e in energy if 0 <= e <= 50]
moderate = [e for e in energy if 51 <= e <= 150]
high = [e for e in energy if e > 150]
invalid = [e for e in energy if e < 0]
valid = [e for e in energy if e >= 0]
total = sum(valid)
buildings = len(valid)
summary = (total, buildings)
if len(high) > 3:
    result = "Overconsumption"
elif abs(len(efficient) - len(moderate)) <= 1:
    result = "Efficient Campus"
elif total > 600:
    result = "Energy Waste Detected"
else:
    result = "Moderate Usage"
expected = students * 0.1
if total <= expected:
    student_result = "Energy consumption is within the range based on the number of students."
else:
    student_result = "Energy consumption exceeds when compared with the number of students."
print("\nSmart Campus Energy Report")
print("Campus:", campus)
print("Generated by:", student)
print("Total Students:", students)
print("\nEfficient readings:", efficient)
print("Moderate readings:", moderate)
print("High readings:", high)
print("Invalid readings:", invalid)
print("\nSummary (Total, Buildings):", summary)
print("Total consumption:", total)
print("Number of buildings:", buildings)
print("\nEfficiency Result:", result)
print("Student Comparison:", student_result)